### ISSUE TITLE
缺少 “v0.4.24-gm.js”文件

### ISSUE THREAD

**Issue by somedisappoint** [WeBankFinTech/WeBASE-Docker#29]
当我按照 https://mp.weixin.qq.com/s/ff8114vppChegJJziuxJfA 中的方式搭建WeBASE-Front的时候，成功在浏览器中访问到节点，但是在使用合约管理-合约IDE的时候，浏览器一直在转圈。使用F12检查，浏览器控制台报错如下
“
Failed to load resource: the server http://xx.xx.xx.xx:5002/WeBASE-Front/static/js/v0.4.24-gm.js responded with a status of 404 ()
"
尝试过换浏览器，还是次问题，与浏览器无关，因此提一个issue，请大家帮忙看一下

**Comment by CodingCattwo** [comment]
通过ctrl + f5 强制刷新浏览器缓存重新加载可尝试恢复，新版本的docker镜像中国密的solidity js文件已替换为v0.4.25-gm.js
