### ISSUE TITLE
不属于群组1的节点启动webase，front报错“create client for group 1 failed! Please check the existence of group 1 of the connected node!”

### ISSUE THREAD

**Issue by somedisappoint** [WeBankFinTech/WeBASE-Docker#30]
使用webase-docker部署多个节点，有部分节点不属于群组1，使用docker run启动的时候，会报错“create client for group 1 failed! Please check the existence of group 1 of the connected node!”。但是该节点不属于群组1，不应该需要新建群组1的客户端

**Comment by CodingCattwo** [comment]
最新版docker镜像已修复该问题
