### ISSUE TITLE
优化了一下部署方式

### ISSUE THREAD

**Issue by currycan** [WeBankFinTech/WeBASE-Docker#32]
参考您的部署,在此基础上做了一些优化:
1. 将 front 和 node 部署在同一个 pod 内,从而不需要另外作镜像
2. 使用 pvc 作为持久化盘,不需要绑定节点,只需要一次复制配置文件
3. 应用配置 configmap 方式,便于修改配置
在: https://github.com/currycan/fisco-webase-k8s

**Comment by susengo** [comment]
> 

大佬可以分享下优化后的部署方案么，感谢！

**Comment by currycan** [comment]
@susengo 上面写了地址：https://github.com/currycan/fisco-webase-k8s

**Comment by currycan** [comment]
close
